import type { Metadata } from "next";
import { inter } from '@/config/fonts';

import "./globals.css";
import { ProviderSessionAuth } from "@/components";

export const metadata: Metadata = {
  title: {
    // * -> Forma de como crear un template y usarlo en titulo de todas las pages 
    template: '%s - Teslo | Shop',
    default: "Home - Teslo | Shop"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderSessionAuth>
          {children}
        </ProviderSessionAuth>
      </body>
    </html>
  );
}
